name: Deployer
description: Composite action to deploy projects on different AWS services
inputs:
  METHOD:
    required: true
    description: Which method will be used to deploy the code (EC2 is the only one on this first stage)
  EC2_IP:
    required: true
    description: IP to connecto to the EC2 server. Ex. ec2-xx-xxx-xxx-x.compute-4.amazonaws.com
  EC2_USER:
    required: true
    description: user to login on EC2 instance
  EC2_KEY:
    required: true
    description: Key to connect to the EC2 Server via SSH
  IMAGE_NAME:
    required: true
    description: Zipped file with the Docker image to be copied and deployed
  COMPOSE_PORTS:
    required: false
    description: Formatted ports for a docker compose structure
  COMPOSE_NETWORKS:
    required: false
    description: Formatted networks for a docker compose structure
  COMPOSE_VOLUMES:
    required: false
    description: Formatted volumes for a docker compose structure
  COMPOSE_FILE_NAME:
    required: true
    description: Name for the new docker compose file to be created
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "Method: ${{ inputs.METHOD }} | Target: ${{ inputs.EC2_USER }}@${{ inputs.EC2_IP }}"
        echo "Image: ${{ inputs.IMAGE_NAME }} | Compose: ${{ inputs.COMPOSE_FILE_NAME }}"

        if [ -z "${{ inputs.METHOD }}" ]; then
          echo "❌ METHOD missing"
          exit 1
        fi

        if [ -z "${{ inputs.EC2_IP }}" ]; then
          echo "❌ EC2_IP missing"
          exit 1
        fi

        if [ -z "${{ inputs.IMAGE_NAME }}" ]; then
          echo "❌ IMAGE_NAME missing"
          exit 1
        fi

        echo "✅ Inputs validated"

    - name: Make scripts executable
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/*.sh
        echo "✅ Scripts ready"

    - name: Setup SSH connection
      shell: bash
      run: |
        if [ "${{ inputs.METHOD }}" != "EC2" ]; then exit 0; fi

        echo "Setting up SSH to ${{ inputs.EC2_IP }}..."
        echo "${{ inputs.EC2_KEY }}" | tr -d '\r' > server_key.pem
        chmod 600 server_key.pem
        mkdir -p ~/.ssh

        ssh-keyscan -H ${{ inputs.EC2_IP }} >> ~/.ssh/known_hosts 2>&1
        if [ $? -ne 0 ]; then
          echo "❌ ssh-keyscan failed"
          exit 1
        fi

        echo "✅ SSH configured"

    - name: Deploy to EC2
      shell: bash
      run: |
        if [ "${{ inputs.METHOD }}" != "EC2" ]; then exit 0; fi

        if [ ! -f "${{ inputs.IMAGE_NAME }}.tar" ]; then
          echo "❌ Image file not found: ${{ inputs.IMAGE_NAME }}.tar"
          exit 1
        fi

        echo "Copying image to EC2..."
        scp -i server_key.pem -o StrictHostKeyChecking=no ${{ inputs.IMAGE_NAME }}.tar ${{ inputs.EC2_USER }}@${{ inputs.EC2_IP }}:/root/
        if [ $? -ne 0 ]; then
          echo "❌ SCP failed"
          exit 1
        fi

        echo "Deploying..."
        ssh -i server_key.pem -o StrictHostKeyChecking=no ${{ inputs.EC2_USER }}@${{ inputs.EC2_IP }} \
          "COMPOSE_PORTS='${{ inputs.COMPOSE_PORTS }}' \
          COMPOSE_NETWORKS='${{ inputs.COMPOSE_NETWORKS }}' \
          COMPOSE_VOLUMES='${{ inputs.COMPOSE_VOLUMES }}' \
          COMPOSE_FILE_NAME='${{ inputs.COMPOSE_FILE_NAME }}' \
          IMAGE_NAME='${{ inputs.IMAGE_NAME }}.tar' \
          bash -s" < ${{ github.action_path }}/scripts/ec2_deploy.sh

        if [ $? -ne 0 ]; then
          echo "❌ Deployment failed"
          exit 1
        fi

        echo "✅ Deployed successfully"