name: Deployer
description: Composite action to deploy projects on different AWS services

inputs:
  EC2_IP:
    required: true
    description: IP to connecto to the EC2 server. Ex. ec2-xx-xxx-xxx-x.compute-4.amazonaws.com
  EC2_KEY:
    required: true
    description: Key to connect to the EC2 Server via SSH.
  DOCKER_IMAGE:
    required: true
    description: Zipped file with the Docker image to be copied and deployed
  COMPOSE_PORTS:
    required: true
    description: Formatted ports for a docker compose structure
  COMPOSE_NETWORKS:
    required: true
    description: Formatted networks for a docker compose structure
  COMPOSE_NAME:
    required: true
    description: Name for the new docker compose file to be created

runs:
  using: "composite"
  steps:

    - name: Make scripts executable
      shell: bash
      run: chmod +x ${{ github.action_path }}/scripts/*.sh

    - name: Preparing PEM Key for SSH Connection
      id: preparing_key
      shell: bash
      run: ${{ github.action_path }}/scripts/ssh_key.sh

    - name: Copying Docker Image
      id: copy
      shell: bash
      run: scp -i server_key.pem ${{ steps.docker_config.outputs.IMAGE_NAME }}.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/root/

    - name: Deploying in EC2 Instance
      id: deploy
      shell: bash
      run: ${{ github.action_path }}/scripts/deploy.sh
